// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJE7csuHKuewzVgAHFnDfZ1waaqz0gC_g',
    appId: '1:800562369400:web:fc7b80cb215bf306936e8d',
    messagingSenderId: '800562369400',
    projectId: 'mobile-intro-27',
    authDomain: 'mobile-intro-27.firebaseapp.com',
    storageBucket: 'mobile-intro-27.appspot.com',
    measurementId: 'G-D8T5Z7XYXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Rwmg9A8qwMjhp7axMOSKCbJGNCaaeTs',
    appId: '1:800562369400:android:151cc1f80b0d022c936e8d',
    messagingSenderId: '800562369400',
    projectId: 'mobile-intro-27',
    storageBucket: 'mobile-intro-27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFDB5OVsQDuj8-Xu5uBTNCwJMYZqt9ZJQ',
    appId: '1:800562369400:ios:d65ccd1b50eb8eb2936e8d',
    messagingSenderId: '800562369400',
    projectId: 'mobile-intro-27',
    storageBucket: 'mobile-intro-27.appspot.com',
    iosClientId: '800562369400-0t6ndm8lt0vuiisd80kumrnm64h31hlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileintro',
  );
}
